### ISSUE TITLE
Contents of each file in Pororo datasets

### ISSUE THREAD

**Issue by csyxwei** [adymaharana/storydalle#4]
Hello, thanks for your great work!

There are many files in your shared pororo datasets, and I want to know which content is stored in each file. For example, is label.py marking the characters that appear in the image and what's the masks folder contains? Can you provide more details about that, thanks very much!

**Comment by adymaharana** [comment]
Hello, thank you for your interest in our work!
The PororoSV dataset has many files that came with the original release in the StoryGAN paper. The files that are needed to train StoryDALL-E are:
- the images within the sub-folders
- the sentence embeddings i.e. `descriptions_vec_512.pkl`, 
- the original captions i.e. `descriptions.csv` or `descriptions.npy` and
We need the additional file `labels.npy` to train the character classification model and evaluate the validation and test sets. The labels were also part of the original release. Most other files in the dataset either came with the original release for StoryGAN, or were used in my previous paper. The `masks` contain automatically generated masks for the scenes in PororoSV, and were created by us. However, we ended up not using it in our work because they tended to be noisy and inaccurate. Let me know if you have more questions!
